hnicke/sodalite

src/mainform.py

Due to a buggy behaviour of the arrow keys they are now disabled.

Disable arrow keys

---

bin/shell-integration.sh
sodalite/__main__.py
sodalite/core/dao.py
sodalite/core/dirhistory.py
sodalite/core/entryaccess.py
sodalite/core/hook.py
sodalite/core/key.py
sodalite/util/environment.py

Improve cd integration

---

Makefile
changelog.md
mypy.ini
requirements.txt
sodalite/core/buffer.py
sodalite/core/dao.py
sodalite/core/dirhistory.py
sodalite/core/entry.py
sodalite/core/entryaccess.py
sodalite/core/entrywatcher.py
sodalite/core/hook.py
sodalite/core/rating.py
sodalite/ui/action.py
sodalite/ui/control.py
sodalite/ui/entrylist.py
sodalite/ui/help.py
sodalite/ui/highlighting.py
sodalite/ui/hookbox.py
sodalite/ui/viewmodel.py
sodalite/util/environment.py
sodalite/util/observer.py

Type checking

---

.flake8
mypy.ini
setup.py
sodalite/core/dao.py
sodalite/core/entry.py
sodalite/core/entryaccess.py
sodalite/core/hook.py
sodalite/core/key.py
sodalite/core/navigate.py
sodalite/ui/filepreview.py
sodalite/ui/help.py
sodalite/ui/highlighting.py
sodalite/ui/mainpane.py
sodalite/ui/viewmodel.py

Type entry

---

sodalite/core/action.py
sodalite/ui/control.py
sodalite/ui/entrylist.py
sodalite/ui/graphics.py
sodalite/ui/help.py
tests/test_entrywatcher.py

Assign broken

---

sodalite/core/entry.py
sodalite/ui/entrylist.py

fix: Fix bug where app would crash when navigating to /tmp

---

README.md
mypy.ini
setup.py
sodalite/__main__.py
sodalite/core/history.py
sodalite/ui/graphics.py

String has no attribute absolute

---

changelog.md
sodalite/__main__.py
sodalite/core/config.py
sodalite/util/env.py
tests/conftest.py

Handle no config found

---

changelog.md
sodalite/core/dao.py

Fix visiting root via ','

---

bin/shell-integration.sh
changelog.md

Fix broken bash integration

---

changelog.md
sodalite/core/buffer.py

Fix delete and yank operations when multiple partitions are involved

---

changelog.md
sodalite/core/buffer.py
sodalite/ui/control.py
sodalite/util/env.py

Paste broken

---

changelog.md
sodalite/ui/control.py
sodalite/ui/graphics.py
sodalite/ui/notify.py

Add notifications after successful operations

---

changelog.md
sodalite/__main__.py
sodalite/core/entrywatcher.py
sodalite/core/navigate.py

Fix filesystem detection

---

.github/workflows/release.yaml

Release process

---

sodalite/ui/theme.py

fix: use brown instead of red highlight color in operate mode

---

.run/sodalite.run.xml
sodalite/core/key.py

Entries without keys

---

sodalite/core/entrywatcher.py
tests/test_entrywatcher.py

fix: fix external filesystem change detection

---

sodalite/core/entrywatcher.py

fix: fix file preview with older versions of watchdog (like 0.9.0)

---

sodalite/__main__.py
sodalite/core/navigate.py

fix: do not crash if env var PWD is not set

---

sodalite/core/key.py

fix: entries which end up having no key get a key reassigned eventually

---

README.md
scripts/sodalite-open
sodalite/core/action.py
sodalite/core/hook.py
sodalite/core/sodalite.conf
sodalite/ui/control.py
sodalite/ui/entrylist.py
sodalite/ui/graphics.py
sodalite/ui/mmode.py
sodalite/ui/notify.py
sodalite/ui/theme.py
sodalite/ui/viewmodel.py
sodalite/util/pubsub.py

fix: replace 'vim' hook with generic 'edit' hook

---

README.md

- fix permission problem
- prevent architecture warnings on "apt-get update"

Improve Debian/Ubuntu Install procedure
